### ISSUE TITLE
Index Out Of Bound. 

### ISSUE THREAD

**Issue by kavikumarN** [jvirtanen/coinbase-fix-example#1]
`Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 64 out of bounds for length 64
	at com.paritytrading.philadelphia.FIXValue.setString(FIXValue.java:261)
	at com.paritytrading.philadelphia.FIXConnection.prepare(FIXConnection.java:251)
	at com.paritytrading.philadelphia.FIXConnection.prepare(FIXConnection.java:232)
	at org.jvirtanen.coinbase.fix.Example.main(Example.java:120)
	at org.jvirtanen.coinbase.fix.Example.main(Example.java:34)
`
Please help me to sort out this issue.

**Comment by jvirtanen** [comment]
Hi @kavikumarN! It looks like the field capacity should be increased from 64 to something suitable, e.g. 128, with `FIXConfig.Builder#setFieldCapacity()`. Would you like to open a pull request for this?
